### ISSUE TITLE
Cannot create worker nodes with CentOS7 and K8S 1.19.1 OVA as template

### ISSUE THREAD

**Issue by ZhangYW18** [kubernetes-sigs/cluster-api-provider-vsphere#1069]
/kind bug

**What steps did you take and what happened:**
I'm using published OVAs (http://storage.googleapis.com/capv-images/release/v1.19.1/centos-7-kube-v1.19.1.ova) as machine template to create a workload cluster with 1 master node (KubeadmControlPlane) and 2 worker nodes in a management cluster. Part of the YAML file generated is like this:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  name: matrix-centos-7-k8s-v1-19-1-build-num-10
  namespace: matrix-centos-7-k8s-v1-19-1-build-num-10
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: SDDC-Datacenter
      datastore: WorkloadDatastore
      diskGiB: 25
      folder: antrea
      memoryMiB: 8192
      network:
        devices:
        - dhcp4: true
          networkName: {my network}
      numCPUs: 2
      resourcePool: {my resourcePool path}
      server: {my vCenter server}
      template: centos-7-kube-v1.19.1
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: matrix-centos-7-k8s-v1-19-1-build-num-10
  name: matrix-centos-7-k8s-v1-19-1-build-num-10-md-0
  namespace: matrix-centos-7-k8s-v1-19-1-build-num-10
spec:
  clusterName: matrix-centos-7-k8s-v1-19-1-build-num-10
  replicas: 2
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: matrix-centos-7-k8s-v1-19-1-build-num-10
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: matrix-centos-7-k8s-v1-19-1-build-num-10-md-0
      clusterName: matrix-centos-7-k8s-v1-19-1-build-num-10
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: VSphereMachineTemplate
        name: matrix-centos-7-k8s-v1-19-1-build-num-10
      version: v1.19.1
```
After applying such YAML, the HAProxyLoadBalancer and the KubeadmControlPlane are created successfully in my vCenter resource pool, but the two worker nodes are not created.
After checking the logs in pods `capv-controller-manager-68cb6ccdff-rk786` and `capi-controller-manager-6d97bcb988-tjhj5`, I found out that maybe the requests for creating the two workers nodes are not received by them --- I searched for `matrix-centos-7-k8s-v1-19-1-build-num-10-md-0`, the worker nodes' name, in the log, and nothing shows.

This problem only appears when using published OVA with CentOS 7 and K8S v1.19.1. When we're using other OVAs with a different K8S version or a different OS, this problem never appears.

**What did you expect to happen:**
The worker nodes to be created.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- HAProxy image version:
```
    template: capv-haproxy-v0.6.3
```
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.4 LTS
