### ISSUE TITLE
CloudConfigSecret should not be reconciled if CloudProviderConfiguration is empty

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#1083]
**Is this a BUG REPORT or FEATURE REQUEST?:**

/kind bug

originally filed by @vijaykatam in https://github.com/kubernetes/cloud-provider-vsphere/issues/431

**What happened:** The controller fails clusters when CloudProviderConfiguration is empty trying to reconcile VSphereCluster.Spec.CloudProviderConfiguration.VCenter

**What you expected to happen:** Controller should skip reconciling cloud-config secret when CloudProviderConfiguration is empty.

**How to reproduce it (as minimally and precisely as possible):** Use a VsphereCluster with the following spec
```
  spec:
    controlPlaneEndpoint:
      host: 10.92.177.12
      port: 6443
    server: 10.92.171.139
    thumbprint: 24:94:49:DD:E3:5F:2F:EF:50:27:27:74:69:54:7C:EC:01:A1:C1:A8
```
**Anything else we need to know?:**

1. This line https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspherecluster_controller.go#L739 should check for CloudProviderConfiguration.
2. https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspherecluster_controller.go#L565 should also check for CloudProviderConfiguration.
3. https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vspherecluster_controller.go#L633 should also check for CloudProviderConfiguration.

**Environment:**

vsphere-cloud-controller-manager version: 1.2.1
OS (e.g. from /etc/os-release): Photon
Kernel (e.g. uname -a): Linux 4.19.150-1.ph3 #1-photon SMP Fri Oct 23 02:29:37 UTC 2020 x86_64 GNU/Linux
Install tools:
Others:
