### ISSUE TITLE
Containers still run as root due to non-numeric user in Docker image

### ISSUE THREAD

**Issue by shysank** [kubernetes-sigs/cluster-api-provider-vsphere#1089]
/kind bug

**What steps did you take and what happened:**
This is a duplicate of [capi non root user bug](https://github.com/kubernetes-sigs/cluster-api/issues/4046)

**What did you expect to happen:**
capv should not fail when psp for non root users is enabled

**Anything else you would like to add:**
[capi fix](https://github.com/kubernetes-sigs/cluster-api/pull/4064)

**Environment:**

- cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
FYI other providers, to test https://github.com/kubernetes-sigs/cluster-api/issues/4046 
create the `kind` management cluster with the following config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      apiServer:
        extraArgs:
          enable-admission-plugins: "PodSecurityPolicy"
```
