### ISSUE TITLE
RBAC deployed for CCM doesnt include leases

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#1113]
/kind bug

**What steps did you take and what happened:**
The RBAC created for just the CCM doesnt include the Rights to read and write leases, thus the CCM deployment will fail.

Adding 
```
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - list
  - get
  - watch
  - create
  - patch
  - update
```
to the ClusterRole will fix it.

**What did you expect to happen:**
The CCM can run and assign ProviderIDs

**Environment:**

- Cluster-api-provider-vsphere version: 0.7.4
