### ISSUE TITLE
Clusters fail to provision volumes: "no available topology found"

### ISSUE THREAD

**Issue by wmedlar** [kubernetes-sigs/cluster-api-provider-vsphere#1150]
/kind bug

**What steps did you take and what happened:**

Volumes are failing to provision for new clusters after upgrading from capv v0.7.1 -> v0.7.6 with the error `failed to provision volume with StorageClass "[storageclass]": error generating accessibility requirements: no available topology found
`. Our StorageClass (see below) does not have any topology restrictions.

**What did you expect to happen:**

VSphere CSI volumes are able to provision and bind.

**Anything else you would like to add:**

The only difference in manifests between 0.7.1 and 0.7.6 is the new addition of `spec.cloudProviderConfiguration.labels` in the VSphereCluster and a version bump for the following images:

* vsphere cpi v1.2.0 -> v1.18.1
* vsphere csi v2.0.0 -> v2.1.0 (driver & syncer) 
* csi attacher v2.2.0 -> v3.0.0
* csi liveness probe v2.0.0 -> v2.1.0
* csi provisioner v1.6.0 -> v2.0.0
* csi node registrar v1.3.0 -> v2.0.1

These match the image versions found in [cloud-controller-manager.go](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/v0.7.6/pkg/services/cloudprovider/cloud-controller-manager.go#L30-L32) and [csi.go](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/v0.7.6/pkg/services/cloudprovider/csi.go#L35-L46) for capv v0.7.6, and these are all using capv-supplied manifests with no customizations, which [includes --feature-gates=Topology=true on the csi-provisioner](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/v0.7.6/pkg/services/cloudprovider/csi.go#L589).

csi-provisioner logs offer no additional information at `--v=8` but does show that topology keys do not exist on any node:
  ```plaintext
  W0319 17:47:25.474242       1 topology.go:292] No topology keys found on any node
  ```
No topology keys exist on nodes in our capv v0.7.1 clusters either, however new volumes are successfully provisioned and bound.

<details>
  <summary>The VSphereCluster</summary>

  ```yaml
  apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
  kind: VSphereCluster
  metadata:
    name: capv-e2e-2380843
  spec:
    cloudProviderConfiguration:
      labels:
        region: k8s-region
        zone: k8s-zone
      providerConfig:
        cloud: [private images versioned as listed above]
    [...]
  ```
</details>

<details>
  <summary>The PVC</summary>

  ```yaml
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: data-prometheus2-0
    namespace: monitoring
    annotations:
      volume.beta.kubernetes.io/storage-provisioner: csi.vsphere.vmware.com
    finalizers:
    - kubernetes.io/pvc-protection
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: nvme-vsphere
    volumeMode: Filesystem
  status:
    phase: Pending
  ```

  ```
  Events:
    Type     Reason                Age                  From                                                                                                 Message
    ----     ------                ----                 ----                                                                                                 -------
    Normal   Provisioning          60s (x8 over 3m7s)   csi.vsphere.vmware.com_vsphere-csi-controller-6bf76c4995-w76lh_3fd7015f-0cfa-4df2-9775-7bac4d9aec59  External provisioner is provisioning volume for claim "monitoring/data-prometheus2-0"
    Warning  ProvisioningFailed    60s (x8 over 3m7s)   csi.vsphere.vmware.com_vsphere-csi-controller-6bf76c4995-w76lh_3fd7015f-0cfa-4df2-9775-7bac4d9aec59  failed to provision volume with StorageClass "nvme-vsphere": error generating accessibility requirements: no available topology found
    Normal   ExternalProvisioning  14s (x13 over 3m7s)  persistentvolume-controller                                                                          waiting for a volume to be created, either by external provisioner "csi.vsphere.vmware.com" or manually created by system administrator
  ```
</details>

<details>
  <summary>The StorageClass</summary>

  ```yaml
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    name: nvme-vsphere
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
  provisioner: csi.vsphere.vmware.com
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  ```
</details>

<details>
  <summary>The CSIDriver</summary>

  ```yaml
  apiVersion: storage.k8s.io/v1beta1
  kind: CSIDriver
  metadata:
    name: csi.vsphere.vmware.com
  spec:
    attachRequired: true
    podInfoOnMount: false
    volumeLifecycleModes:
    - Persistent
  ```
</details>

<details>
  <summary>The CSINode</summary>

  ```yaml
  apiVersion: storage.k8s.io/v1
  kind: CSINode
  metadata:
    name: capv-e2e-2380843-7gz2d
    ownerReferences:
    - apiVersion: v1
      kind: Node
      name: capv-e2e-2380843-7gz2d
  spec:
    drivers:
    - name: csi.vsphere.vmware.com
      nodeID: capv-e2e-2380843-7gz2d
      topologyKeys: null
  ```
</details>

<details>
  <summary>The Node</summary>

  ```yaml
apiVersion: v1
kind: Node
metadata:
  name: capv-e2e-2380843-7gz2d
  annotations:
    csi.volume.kubernetes.io/nodeid: '{"csi.vsphere.vmware.com":"capv-e2e-2380843-7gz2d"}'
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  labels:
    failure-domain.beta.kubernetes.io/region: our-datacenter
    failure-domain.beta.kubernetes.io/zone: our-cluster
    topology.kubernetes.io/region: our-datacenter
    topology.kubernetes.io/zone: our-cluster
spec:
  podCIDR: 10.74.160.0/24
  podCIDRs:
  - 10.74.160.0/24
  providerID: vsphere://42217b2e-096a-e41e-eee7-1cc607d99e76
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  nodeInfo:
    architecture: amd64
    containerRuntimeVersion: containerd://1.3.4
    kernelVersion: 4.15.0-112-generic
    kubeProxyVersion: v1.17.11
    kubeletVersion: v1.17.11
    operatingSystem: linux
    osImage: Ubuntu 18.04.5 LTS
  ```
</details>

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.6

- Kubernetes version: (use `kubectl version`): 
  ```shell
  $ kubectl version 
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:11:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  ```

- OS (e.g. from `/etc/os-release`): 
  ```shell
  $ cat /etc/os-release
  NAME="Ubuntu"
  VERSION="18.04.5 LTS (Bionic Beaver)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 18.04.5 LTS"
  VERSION_ID="18.04"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=bionic
  UBUNTU_CODENAME=bionic
  ```
