### ISSUE TITLE
Max pods on a node

### ISSUE THREAD

**Issue by simha5009** [kubernetes-sigs/cluster-api-provider-vsphere#1238]
/kind feature

**Describe the solution you'd like**
Can we add max-pod support on the machines/nodes?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.10
- Kubernetes version: (use `kubectl version`): all
- OS (e.g. from `/etc/os-release`): all

**Comment by vrabbi** [comment]
@simha5009 this is possible already via the kubeadmconfigtemplate and kubeadmcontrolplane crds.
this is done by adding in the kubeletExtraArgs section an arg called "maxPods"
an example bellow is how you could set it in a kubeadmconfigtemplate:
```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: capv-cls-01-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: "/var/run/containerd/containerd.sock"
          kubeletExtraArgs:
            maxPods: 50
            cloud-provider: external
            tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
          name: "{{ ds.meta_data.hostname }}"
      preKubeadmCommands:
      - hostname "{{ ds.meta_data.hostname }}"
      - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
      - echo "127.0.0.1   localhost" >>/etc/hosts
      - echo "127.0.0.1   {{ ds.meta_data.hostname }}" >>/etc/hosts
      - echo "{{ ds.meta_data.hostname }}" >/etc/hostname
      useExperimentalRetryJoin: true
      users:
      - name: capv
        sshAuthorizedKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAAD..............................................
```
