### ISSUE TITLE
🐛 Add `storagePolicyName` field to the `/templates/cluster-template.yaml` file

### ISSUE THREAD

**Issue by AartiJivrajani** [kubernetes-sigs/cluster-api-provider-vsphere#1245]
/kind bug

**What steps did you take and what happened:**
`storagePolicyName` is missing in the templates file [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/templates/cluster-template.yaml). 
We need to add 
```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: VSphereMachineTemplate
metadata:
  name: '${CLUSTER_NAME}'
  namespace: '${NAMESPACE}'
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: '${VSPHERE_DATACENTER}'
      datastore: '${VSPHERE_DATASTORE}'
      diskGiB: 25
      folder: '${VSPHERE_FOLDER}'
      memoryMiB: 8192
      network:
        devices:
        - dhcp4: true
          networkName: '${VSPHERE_NETWORK}'
      numCPUs: 2
      resourcePool: '${VSPHERE_RESOURCE_POOL}'
      server: '${VSPHERE_SERVER}'
      storagePolicyName: '${VSPHERE_STORAGE_POLICY}'       <------------- add this field here
      template: '${VSPHERE_TEMPLATE}'
```

/assign
