### ISSUE TITLE
Patching VSphereCluster resource doesn't reconcile vccm configmap

### ISSUE THREAD

**Issue by mantipin** [kubernetes-sigs/cluster-api-provider-vsphere#1293]
/kind bug

**What steps did you take and what happened:**

We tried to add labels (region: k8s-region, zone: k8s-zone) on our running cluster from vmware tags by editing VSphereCluster manifest, adding "labels" block:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereCluster
metadata:
  name: cluster
spec:
  cloudProviderConfiguration:
    labels:
      region: k8s-region
      zone: k8s-zone
    ...
```

**What did you expect to happen:**
Labels appear on nodes or even in vsphere-cloud-config configmap on workload cluster

**Anything else you would like to add:**
No labels appear on already existing cluster. Even if we change `spec.cloudProviderConfiguration.workspace.resourcePool`, nothing happens.
When we deploy brand-new cluster with this VSphereCluster manifest (with labels), it deploys with topology labels, based on vmware tags. 
I found that configmap named `vsphere-cloud-config` in kube-system namespace on workload cluster didn't changed after editing vspherecluster resource - there must be new block, starting with [Labels].

My question in k8s-slack: https://kubernetes.slack.com/archives/CKFGK3SSD/p1635830093063600

**Environment:**

- Cluster-api-provider-vsphere version: CAPI and CAPV versions are: v0.7.10, cloud-provider-vsphere version is v1.18.1
- Kubernetes version: (use `kubectl version`):  Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.6 LTS
