### ISSUE TITLE
CAPV ControlPlane Failure Domain documentation

### ISSUE THREAD

**Issue by dimatha** [kubernetes-sigs/cluster-api-provider-vsphere#1312]
/kind feature

**Describe the solution you'd like**
As a cluster admin I'd like to distribute k8s CP nodes across different hosts within the same cluster.

Referring to this proposal: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/proposal/20201103-failure-domain.md#for-user-story-1
I'm struggling to understand how to do the configuration using VSphereFailureDomain CRD to achieve the goal.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v0.8.1
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by dimatha** [comment]
Ok, I had to spend some time to understand it. And here is my experience.

From the proposal:

```
Region -> ComputeCluster, Zone -> HostGroup
#no tag required
#hostgroups need to be pre-configured
#CAPV need permissions to create vm groups and affinity rules
```
From my experience: 

- Create vCenter Tags and categories
- Create Host Groups
- Create VM groups with a dummy VM as it can't be empty
- Create VM to Host rules
- Create CAPV resources: VSphereDeploymentZone => VSphereFailureDomain
- make sure VSphereDeploymentZone is ready
- no need to reference VSphereDeploymentZone from the CP
- assigned zone should be visible from the Machine spec.failureDomain
- all ready VSphereDeploymentZones should be visible from the Cluster status.failureDomains

**Comment by ksemele** [comment]
Hello everyone! Do we have any updates for this task? I tried to understand this part too, but it wasn't easy. Here is my work (and cleaned) example for the FluxCD Kustomization template, but I can't clearly explain to my infra team the specific requirements for vSphere tags and zone naming, for example, without a documentation reference. Also, I don't have answers for "What happens when we add or remove a zone?" and other questions.

```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereDeploymentZone
metadata:
  name: ${VSPHERE_DATACENTER}-${ZONE}
  labels:
    datacenter: ${VSPHERE_DATACENTER}
    zone: ${ZONE}
spec:
  controlPlane: true
  failureDomain: ${VSPHERE_DATACENTER}-${ZONE}
  placementConstraint:
    folder: ${VSPHERE_FOLDER}
    resourcePool: ${VSPHERE_DATACENTER}-${ZONE}/Resources
  server: ${VSPHERE_SERVER}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereFailureDomain
metadata:
  name: ${VSPHERE_DATACENTER}-${ZONE}
  labels:
    datacenter: ${VSPHERE_DATACENTER}
    zone: ${ZONE}
spec:
  region:
    name: ${REGION}
    type: Datacenter
    tagCategory: k8s-region
  zone:
    name: ${ZONE}
    type: ComputeCluster
    tagCategory: k8s-zone
  topology:
    datacenter: ${VSPHERE_DATACENTER}
    datastore: ${VSPHERE_DATASTORE}
    computeCluster: ${VSPHERE_DATACENTER}-${ZONE}
```

How can I help the community with those docs?
PS thanks to @dimatha for a clue...
