### ISSUE TITLE
bug: generated kubadm token includes log output

### ISSUE THREAD

**Issue by ntfrnzn** [kubernetes-sigs/cluster-api-provider-vsphere#145]
I’m observing a problem with the workers being unable to join a cluster because they haven an invalid token.

In fact, the /tmp/boot.sh script includes
```
TOKEN=I1204 04:46:06.528320      24 version.go:236] remote version is much newer: v1.13.0; falling back to: stable-1.12
ewe864.2i8qadn9rz541i84
```

Log output is prepended to the actual token value

The create-token utility is here:
https://github.com/kubernetes-sigs/cluster-api/blob/e1903be683739379be57f78a4095cd51726495fd/pkg/kubeadm/kubeadm.go#L56

and used:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/fd4d9e1385779fae41393eeae59614ef12490059/pkg/cloud/vsphere/provisioner/govmomi/utils.go#L56

controller log output:
```
I1204 04:46:10.310625       1 controller.go:124] reconciling cluster a3824d30-8bf2-4a34-9645-655273c05fb5 triggers idempotent reconcile.
I1204 04:46:10.311929       1 utils.go:73] Generated kubeadm token I1204 04:46:06.528320      24 version.go:236] remote version is much newer: v1.13.0; falling back to: stable-1.12
ewe864.2i8qadn9rz541i84 from master
```

It's not clear why the log text is being included now.  It would be safer to generate the token in a programmatic way, but if we want to parse stdout, then a regexp can be used
```
KubeadmTokenPattern     = regexp.MustCompile(`(?m)[a-z0-9]{6}\.[a-z0-9]{16}`)
token = KubeadmTokenPattern.FindString(output)
```

**Comment by ntfrnzn** [comment]
sample master machine definitions which is at least similar to the one that involved in the problem
```
apiVersion: cluster.k8s.io/v1alpha1
kind: Machine
metadata:
  annotations:
    vm-ip-address: 10.68.192.46
  creationTimestamp: "2018-12-04T21:28:57Z"
  finalizers:
  - machine.cluster.k8s.io
  generateName: ef496a1fcaef-master-1-
  generation: 2
  name: ef496a1fcaef-master-1-6j8wk
spec:
  metadata:
    creationTimestamp: null
  providerConfig:
    value:
      apiVersion: vsphereproviderconfig.sigs.k8s.io/v1alpha1
      kind: VsphereMachineProviderConfig
      machineRef: vm-2248
      machineSpec:
        datacenter: NetApp-HCI-Datacenter
        datastore: NetApp-HCI-Select-Data-04-01
        disks:
        - diskLabel: Hard disk 1
          diskSizeGB: 50
        memoryMB: 4096
        networks:
        - ipConfig:
            networkType: dhcp
          networkName: VM_Network
        numCPUs: 2
        resourcePool: Resources
        template: ubuntu-cloudimg-template
      metadata:
        creationTimestamp: null
  versions:
    controlPlane: 1.11.5
    kubelet: 1.11.5
status:
  providerStatus:
    lastUpdated: 2018-12-04 21:29:11.806427777 +0000 UTC
    taskRef: ""
```

I don't think there's anything unique about the template _ubuntu-cloudimg-template_, pretty vanilla ubuntu iirc.
