### ISSUE TITLE
capv-manager-bootstrap-credentials secret template should support vSphere password with single quote

### ISSUE THREAD

**Issue by prkalle** [kubernetes-sigs/cluster-api-provider-vsphere#1460]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If vSphere password contains single quote `'` it is causing error while unmarshaling the credentials.yaml in `capv-manager-bootstrap-credentials` secret.

The below is the template for "capv-manager-bootstrap-credentials" secret in infrastructure-components.yaml. Since the password contains single quote(') it causing the issues while unmarshaling the credentials.yaml.

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
  name: capv-manager-bootstrap-credentials
  namespace: capv-system
stringData:
  credentials.yaml: |-
    username: '${VSPHERE_USERNAME}'
    password: '${VSPHERE_PASSWORD}'
type: Opaque
```

**What did you expect to happen:**
capv-manager-bootstrap-credentials secret should support vSphere password with single quote and should not cause issue while unmarshaling the credentials.yaml

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version:  v1.0.2
- Kubernetes version: (use `kubectl version`): v1.18.2
- OS (e.g. from `/etc/os-release`):

**Comment by prkalle** [comment]
Tried removing the single quotes in the template as shown below. It didn't work for passwords starting with single quote(') and %.

```
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
  name: capv-manager-bootstrap-credentials
  namespace: capv-system
stringData:
  credentials.yaml: |-
    username: ${VSPHERE_USERNAME}
    password: ${VSPHERE_PASSWORD}
type: Opaque
```
