### ISSUE TITLE
Unable to get three managers nodes to provision - Machines getting stuck in "Provisioned" state

### ISSUE THREAD

**Issue by steve-fraser** [kubernetes-sigs/cluster-api-provider-vsphere#1487]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Follow quick start guide.

**What did you expect to happen:**

It seems that the Kubeadmcontrolplanes is showing replicas in the ready state
```
NAME                   CLUSTER                INITIALIZED   API SERVER AVAILABLE   REPLICAS   READY   UPDATED   UNAVAILABLE   AGE     VERSION
profiles-vsphere-477   profiles-vsphere-477   true          true                   1          1       1         0             7m26s   v1.17.3
```
with the conditions being
```
status:
  conditions:
  - lastTransitionTime: "2022-03-22T15:27:38Z"
    message: Scaling up control plane to 3 replicas (actual 1)
    reason: ScalingUp
    severity: Warning
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-03-22T15:28:52Z"
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-22T15:27:32Z"
    status: "True"
    type: CertificatesAvailable
  - lastTransitionTime: "2022-03-22T15:28:32Z"
    status: "True"
    type: MachinesReady
  - lastTransitionTime: "2022-03-22T15:27:38Z"
    message: Scaling up control plane to 3 replicas (actual 1)
    reason: ScalingUp
    severity: Warning
    status: "False"
    type: Resized
  initialized: true
```
It seems machines are getting stuck in the "Provisioned" state and not moving to the "Running" state
```
NAME                                         CLUSTER                NODENAME   PROVIDERID                                       PHASE         AGE    VERSION
profiles-vsphere-477-dzcv6                   profiles-vsphere-477              vsphere://421ea2d9-ea3e-e7ad-7a93-d27d782ef8d5   Provisioned   9m5s   v1.17.3
profiles-vsphere-477-md-0-56678b97c4-vt7cr   profiles-vsphere-477              vsphere://421ec23e-b9c6-ed3e-a6cb-f0b3cd5c9484   Provisioned   9m6s   v1.17.3
```
However, everything seems to be coming up properly.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Single ESXI Host with vsphere
**Environment:**

- Cluster-api-provider-vsphere version:  v1.1.1
- Kubernetes version: (use `kubectl version`): v1.17.3 
- OS (e.g. from `/etc/os-release`): 
ubuntu-1804-kube-v1.17.3
