### ISSUE TITLE
storagePolicyName (and datastore) at disk level

### ISSUE THREAD

**Issue by sathieu** [kubernetes-sigs/cluster-api-provider-vsphere#1538]
/kind feature

**Describe the solution you'd like**

`VSphereMachine` kind only allows to set storage policy globally. It is recommended to store etcd data on a disk with low latency (see #894), and other usage may need encrypted disk for some data.

Proposal, add a new `disks` field (and deprecate `diskGiB` and `additionalDisksGiB`). Example:

```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: '{{ $cluster.cluster_name }}-worker'
  namespace: '{{ $cluster.namespace }}'
spec:
  template:
    spec:
      disks:
      - {} # primary disk unchanged
      - sizeGiB: 10  # for etcd
        storagePolicyName: FastSSD
      - sizeGiB: 20
```

This has the additional benefit of allowing future extra fields (datastore, disk provisioning, sharing, shares, ...)

**Anything else you would like to add:**

For reference, here are the current relevant fields:

```console
$ kubectl explain vspheremachine.spec.additionalDisksGiB
KIND:     VSphereMachine
VERSION:  infrastructure.cluster.x-k8s.io/v1beta1

FIELD:    additionalDisksGiB <[]integer>

DESCRIPTION:
     AdditionalDisksGiB holds the sizes of additional disks of the virtual
     machine, in GiB Defaults to the eponymous property value in the template
     from which the virtual machine is cloned.
$ kubectl explain vspheremachine.spec.storagePolicyName
KIND:     VSphereMachine
VERSION:  infrastructure.cluster.x-k8s.io/v1beta1

FIELD:    storagePolicyName <string>

DESCRIPTION:
     StoragePolicyName of the storage policy to use with this Virtual Machine
```

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):
