### ISSUE TITLE
VSphereCluster Server should support IPv6 addresses without brackets

### ISSUE THREAD

**Issue by christianang** [kubernetes-sigs/cluster-api-provider-vsphere#1997]
/kind feature

**Describe the solution you'd like**

I'd like to be able to specify the vSphere server as an IPv6 address, which would be consistent with the control plane endpoint field.

```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  name: my-cluster
spec:
  server: fd01:0:106:b:0:a:0:c20 # this causes a failure
  controlPlaneEndpoint:
    host: fd01:0:106:b:0:a:cccc:fe9a # this works
    port: 6443
```

Currently if I specify this in my cluster I see this error:

```
E0712 21:31:07.578695       1 service.go:65] "capv-controller-manager/vspherecluster-controller/default/my-cluster: error fetching session" err="error parsing vSphere URL \"fd01:0:106:b:0:a:0:c20\": parse \"https://fd01:0:106:b:0:a:0:c20\": invalid port \":c20\" after host" object="my-cluster" namespace="default"
E0712 21:31:07.579835       1 clustermodule_reconciler.go:120] "capv-controller-manager/vspherecluster-controller/default/my-cluster: failed to create cluster module for target object" err="error parsing vSphere URL \"fd01:0:106:b:0:a:0:c20\": parse \"https://fd01:0:106:b:0:a:0:c20\": invalid port \":c20\" after host" name="my-cluster"
```

**Anything else you would like to add:**

The Server field does support brackets, but it is inconsistent with control plane endpoint and other components, such as cloud-provider-vsphere, assume a server address without brackets.

**Environment:**

- Cluster-api-provider-vsphere version: v1.7.0
- Kubernetes version: (use `kubectl version`): 
```
lient Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"83112f368344a8ff6d13b89f120d5e646cd3bf19", GitTreeState:"clean", BuildDate:"2023-06-26T06:47:19Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"83112f368344a8ff6d13b89f120d5e646cd3bf19", GitTreeState:"clean", BuildDate:"2023-06-26T06:42:01Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.6 LTS 5.4.0-152-generic
