### ISSUE TITLE
Multiple clusters per zone

### ISSUE THREAD

**Issue by hrbasic** [kubernetes-sigs/cluster-api-provider-vsphere#2009]
/kind feature

**Describe the solution you'd like**
Option to specify multiple compute clusters per zone. 
Currently when you create vsphere failure domain you can specify only single compute cluster in `vspherefailuredomain.spec.topology`.  

We can specify multiple compute cluster, e.g.

```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereFailureDomain
metadata:
 name: "zone1" 
spec:
 region:
   name: "datacenter1"
   type: Datacenter
   tagCategory: k8s-region 
   autoConfigure: false 
 zone:
   name: "cluster1"
   type: ComputeCluster
   tagCategory: k8s-zone
   autoConfigure: false
 topology:
   datacenter: "datacenter1" 
   # datastore is optional and should\can be set when only one compute cluster is set
   # or we should use storage policy
   datastore: "datastore1" # string - What datastore should be used (optiona)
   # computeClusters is optional and should be set just when one of the 
   # configurations of .spec.zone or .spec.region have a type of ComputeCluster
   computeClusters: 
   - "cluster1" # *string - What cluster should be used
   - "cluster2" # *string - What cluster should be used
   networks: # Networks
   - network1
   - network2
```

In case where multiple clusters are defined, CAPV should find datastore (tagged with k8s-zone) and clone virtual machine on datastore which is accessible from node in the cluster. Scheduling pods between workloads should not be a problem, unless workload is stateful, in that case shared datastore should be used (all clusters in the zone should have access to the shared datastore)

# Use Cases

## Use case 1

Each VMWare compute cluster has datastore for VMs (where K8S VMs will be scheduled). Three vSphere Deployment Zones are created according to VMware zones. K8S VMs can be deployed on all clusters in the zone. CAPV will find datastore which is accessible from the cluster\node and it will clone VM on that datastore.   

Zone A 
 - Compute Cluster A 
 - Compute Cluster B 

Zone B
 - Compute Cluster A
 - Compute Cluster B

Zone C
 - Compute Cluster A 
 - Compute Cluster B
