### ISSUE TITLE
Creating a machine without clusters.k8s.io/cluster-name prevents the machine from being deleted

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#219]
If I create a machine that doesn't have a label, `cluster.k8s.io/cluster-name`, a machine object is created and no VM is created.  If I then try to delete the machine, the machine is never deleted.

During create, the logs shows,

```
I0305 21:19:02.213133       1 controller.go:115] Running reconcile Machine for node-1
I0305 21:19:02.213166       1 controller.go:198] Machine "node-1" in namespace "cluster.k8s.io/cluster-name" doesn't specify "default" label, assuming nil cluster
E0305 21:19:02.213181       1 controller.go:169] Error checking existence of machine instance for machine object node-1; cluster is nil, make sure machines have `clusters.k8s.io/cluster-name` label set and the name references a valid cluster name in the same namespace
```

This is repeated over and over.  The reconcile loop doesn't seem to handle error conditions well.  This is not the issue that this bug is addressing.  The bug comes when it's time to delete the machine.  The machine never gets deleted.  Instead, I get the following in the controller logs:

```
I0305 21:19:56.923096       1 controller.go:147] reconciling machine object node-1 triggers delete.
E0305 21:19:56.923218       1 controller.go:149] Error deleting machine object node-1; cluster is nil, make sure machines have `clusters.k8s.io/cluster-name` label set and the name references a valid cluster name in the same namespace
```

The machine yaml:

```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineList
items:
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    name: node-1
#    namespace: test
#    labels:
#      cluster.k8s.io/cluster-name: test1
  spec:
    providerSpec:
      value:
        apiVersion: "vsphereproviderconfig/v1alpha1"
        kind: "VsphereMachineProviderConfig"
        vsphereMachine: "standard-node"
        machineSpec:
          datacenter: "vicdc"
          datastore: "datastore108"
          resourcePool: "kube-resource-pool"
          networks:
          - networkName: "VM Network"
            ipConfig:
              networkType: dhcp
              ip: ""
              netmask: ""
              gateway: ""
              dns:
          numCPUs: 2
          memoryMB: 2048
          template: "xenial-server-cloudimg-amd64"
          disks:
          - diskLabel: "Hard disk 1"
            diskSizeGB: 20
          preloaded: false
    versions:
      kubelet: 1.11.3
      controlPlane: 1.11.3
    roles:
    - Node
```
