### ISSUE TITLE
Created machines do not show up as nodes when running `kubectl get node`

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#220]
I create a worker machine.  The machine object shows up when running `kubectl get machines` but does not show up when running `kubectl get nodes`.  This appears to be a recent development as I believe it used to work.

```
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineList
items:
- apiVersion: "cluster.k8s.io/v1alpha1"
  kind: Machine
  metadata:
    name: node-1
    labels:
      cluster.k8s.io/cluster-name: test1
  spec:
    providerSpec:
      value:
        apiVersion: "vsphereproviderconfig/v1alpha1"
        kind: "VsphereMachineProviderConfig"
        vsphereMachine: "standard-node"
        machineSpec:
          datacenter: "vicdc"
          datastore: "datastore108"
          resourcePool: "kube-resource-pool"
          networks:
          - networkName: "VM Network"
            ipConfig:
              networkType: dhcp
              ip: ""
              netmask: ""
              gateway: ""
              dns:
          numCPUs: 2
          memoryMB: 2048
          template: "xenial-server-cloudimg-amd64"
          disks:
          - diskLabel: "Hard disk 1"
            diskSizeGB: 20
          preloaded: false
    versions:
      kubelet: 1.11.3
      controlPlane: 1.11.3
    roles:
    - Node
```
