### ISSUE TITLE
vsphere-csi-node crash with cilium cni

### ISSUE THREAD

**Issue by habibullinrsh** [kubernetes-sigs/cluster-api-provider-vsphere#2682]
kind/bug

**What steps did you take and what happened:**

1. Initialization of cluster management:
`clusterctl -n cluster-api init --infrastructure vsphere --config clusterctl.yaml --addon helm`
2. Generating a cluster from a latest version of cluster-template.yaml:
`clusterctl generate cluster -n k8s-test-cluster k8s-test-cluster --config clusterctl.yaml --control-plane-machine-count=1 --worker-machine-count=3 --from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/download/v1.9.0/cluster-template.yaml > k8s-test-cluster.yaml`
3. Add a parameter to KubeadmControlPlane:
```
    initConfiguration:
      ...
      skipPhases:
        - addon/kube-proxy
```
4. Starting the cluster:
`kubectl apply -f k8s-test-cluster.yaml`
5. Install silium from the helm repository on the master node:
```
helm repo add cilium https://helm.cilium.io
helm show values cilium/cilium --version 1.15.0 > cilium-1.15.0.yaml
values.yaml
          kubeProxyReplacement: "true"
          k8sServiceHost: "100.100.100.25"
          k8sServicePort: "6443"
          hubble:
            enabled: false
          operator:
            replicas: 1
```
Everything works fine in this configuration.
Next, I reboot any worker node and get vsphere-csi-node errors on this node.
![image](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/61868780/e748422e-2187-407d-b909-0fe786749b31)

Pod logs:
![image](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/61868780/db71e348-fa6e-4548-bb85-ce389069b397)

Kubelet logs:
![image](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/61868780/52a049f5-88b3-4e8d-876c-255af33612fa)

But if I install calico with kube-proxy, then everything works:
`kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml`

Has anyone encountered it?

**Environment:**
- cluster-api-provider-vsphere version: 1.9.0
- kubernetes: v1.28.0
- cilium chart: 1.5.0
- image: ubuntu-2204-kube-v1.28.0
