### ISSUE TITLE
Consider updating or dropping cert-manager image loads in vsphere.yaml

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#3046]
We should either load the correct images, or just drop them from the file:
```yaml
  - name: quay.io/jetstack/cert-manager-cainjector:v1.12.2
    loadBehavior: tryLoad
  - name: quay.io/jetstack/cert-manager-webhook:v1.12.2
    loadBehavior: tryLoad
  - name: quay.io/jetstack/cert-manager-controller:v1.12.2
    loadBehavior: tryLoad
```

I don't know if there is any upside to loading the images in the test-framework instead of just with regular pulls *in CAPV*

(Definitely no upside in loading the wrong images :joy:)
