### ISSUE TITLE
Insecure configuration by default

### ISSUE THREAD

**Issue by p0sql** [kubernetes-sigs/cluster-api-provider-vsphere#3416]
/kind bug

**Security concerns in the documentation**
The current configuration of CAPV in the documentation is insecure and very dangerous (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/getting_started.md). 
_VSPHERE_USERNAME_ contains a vsphere user with full admin privileges (no problems).

_VSPHERE_USERNAME_ and _VSPHERE_PASSWORD_ are used in clusterctl.yaml to deploy a workload cluster and these privileges are also used by the CSI because it is the same user as in _VSPHERE_USERNAME_ variable in the CSI configuration. 
In case of a workload cluster compromise, an attacker will have full admin privileges on vCenter API using CSI privileges, this component does not need to create virtual machines or manage networks with NSX for example. In the documentation, **you should indicate the creation of  less privileged user in the CSI configuration**. 

**Mitigations**
Step 1
Building a specific template to replace ${VSPHERE_USERNAME} by ${VSPHERE_CSI_USERNAME}, same thing for password in **cloud-provider-vsphere-credentials** and **vsphere-config-secret** secrets object.
Then, you can add these 2 parameters to _clusterctl.yaml_ to add a user dedicated to the CSI : 
- VSPHERE_CSI_USERNAME: "csi-user" 
- VSPHERE_CSI_PASSWORD: "xxxxxxx"

vsphere-config-secret :
```yaml
apiVersion: v1
kind: Secret
metadata: 
  name: vsphere-config-secret
  namespace: '${NAMESPACE}'
stringData:
  data: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: vsphere-config-secret
      namespace: vmware-system-csi
    stringData:
      csi-vsphere.conf: |+
        [Global]
        thumbprint = "${VSPHERE_TLS_THUMBPRINT}"

        [VirtualCenter "${VSPHERE_SERVER}"]
        user = "${VSPHERE_CSI_USERNAME}"
        password = "${VSPHERE_CSI_PASSWORD}"
        datacenters = "${VSPHERE_DATACENTER}"

        [Network]
        public-network = "${VSPHERE_NETWORK}"

    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
```
cloud-provider-vsphere-credentials :
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-vsphere-credentials
  namespace: '${NAMESPACE}'
stringData:
  data: |-
    apiVersion: v1
    kind: Secret
    metadata:
      labels:
        component: cloud-controller-manager
        vsphere-cpi-infra: secret
      name: cloud-provider-vsphere-credentials
      namespace: kube-system
    stringData:
      ${VSPHERE_SERVER}.password: "${VSPHERE_CSI_PASSWORD}"
      ${VSPHERE_SERVER}.username: "${VSPHERE_CSI_USERNAME}"
    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
```

Step 2
Configure the CSI user with these privileges to avoid full admin privileges on vCenter API :
Profile-driven storage > Profile-driven storage view
Virtual machine > Configuration > Add existing disk 
Virtual Machine > Configuration > Add or remove device 
Datastore > Low level file operations 
Read-only > Default Role 
Cns > Searchable

![Image](https://github.com/user-attachments/assets/560a3a39-a807-45dd-ab67-b20422a9dedd)

PVCs are working correctly using non admin privileges, I have no issues in logs of vsphere-csi-controller pod.

**Environment:**
- vCenter: "Version: 7.0.3 Build: 24322018 "
- Cluster-api-provider-vsphere version: v1.12.0
- Kubernetes version: v1.30.0
- OS: VMware Photon OS 5

Thank you.
