### ISSUE TITLE
Deleting the cluster object takes too long and often fails

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#40]
When deleting an existing target cluster, clusterctl usually takes 10s of minutes or simply times out trying the last step in the workflow -- delete cluster objects.  The suspicion is that the cluster object has too many finalizers as shown in the snippet below,

```
apiVersion: cluster.k8s.io/v1alpha1
kind: Cluster
metadata:
  creationTimestamp: 2018-09-10T23:00:58Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2018-09-10T23:01:59Z
  finalizers:
  - cluster.cluster.k8s.io
  - cluster.cluster.k8s.io
  - cluster.cluster.k8s.io
```

The above is from the cluster object on the bootstrap cluster.
