### ISSUE TITLE
unable to create control plane machine: timed out waiting for the condition

### ISSUE THREAD

**Issue by vincenthanjs** [kubernetes-sigs/cluster-api-provider-vsphere#415]
/kind bug

**What steps did you take and what happened:**

root@ubuntu:~/cluster-api-provider-vsphere/out/my-cluster# clusterctl create cluster --provider vsphere --bootstrap-type kind -c cluster.yaml -m machines.yaml -p provider-components.yaml --addon-components addons.yaml
I0705 21:16:09.041966   10874 createbootstrapcluster.go:27] Preparing bootstrap cluster
I0705 21:17:41.882087   10874 clusterdeployer.go:78] Applying Cluster API stack to bootstrap cluster
I0705 21:17:41.884219   10874 applyclusterapicomponents.go:26] Applying Cluster API Provider Components
I0705 21:17:43.956165   10874 clusterdeployer.go:83] Provisioning target cluster via bootstrap cluster
I0705 21:17:43.980221   10874 applycluster.go:36] Creating cluster object my-cluster in namespace "default"
I0705 21:17:43.994916   10874 clusterdeployer.go:92] Creating control plane machine in namespace "default"
I0705 21:17:44.011372   10874 applymachines.go:36] Creating machines in namespace "default"
I0705 21:47:44.047698   10874 createbootstrapcluster.go:36] Cleaning up bootstrap cluster.
F0705 21:47:46.274402   10874 create_cluster.go:61] unable to create control plane machine: timed out waiting for the condition

**Environment:**

- Cluster-api-provider-vsphere version: 0.3
- Kubernetes version: (use `kubectl version`): 
root@ubuntu:~/cluster-api-provider-vsphere/out/my-cluster# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): 
root@ubuntu:~/cluster-api-provider-vsphere/out/my-cluster# uname -a
Linux ubuntu 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ykakarap** [comment]
@vincenthanjs Can you please provide the `machines.yaml` file used.

**Comment by tkrausjr** [comment]
I am having the same issue. See below. 
```
root@ubu01-jumphost:/tmp/tmp.f6KPgZUKW3/out/capv-bootstrap# clusterctl create cluster --provider vsphere --bootstrap-type kind -c cluster.yaml -m machines.yaml -p provider-components.yaml --addon-components addons.yaml
I0709 13:18:29.967692    8051 createbootstrapcluster.go:27] Preparing bootstrap cluster
I0709 13:20:44.987710    8051 clusterdeployer.go:78] Applying Cluster API stack to bootstrap cluster
I0709 13:20:44.987743    8051 applyclusterapicomponents.go:26] Applying Cluster API Provider Components
I0709 13:20:46.556128    8051 clusterdeployer.go:83] Provisioning target cluster via bootstrap cluster
I0709 13:20:46.568293    8051 applycluster.go:36] Creating cluster object capv-bootstrap in namespace "default"
I0709 13:20:46.577750    8051 clusterdeployer.go:92] Creating control plane machine in namespace "default"
I0709 13:20:46.584146    8051 applymachines.go:36] Creating machines in namespace "default"
I0709 13:50:46.623986    8051 createbootstrapcluster.go:36] Cleaning up bootstrap cluster.
F0709 13:50:48.000230    8051 create_cluster.go:61] unable to create control plane machine: timed out waiting for the condition
```
My machines.yaml file being used:
```
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineList
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    name: "capv-bootstrap-controlplane-1"
    labels:
      cluster.k8s.io/cluster-name: "capv-bootstrap"
  spec:
    providerSpec:
      value:
        apiVersion: vsphere.cluster.k8s.io/v1alpha1
        kind: VsphereMachineProviderSpec
        datacenter: "Datacenter"
        datastore: "ISCSI-DATASTORE"
        resourcePool: "*/Physical-CAPV"
        folder: "capv_vms"
        network:
          devices:
          - networkName: "VLAN 1526"
            dhcp4: true
            dhcp6: false
        numCPUs: 2
        memoryMiB: 2048
        diskGiB: 20
        template: "ubuntu-1804-template"
    versions:
      kubelet: "1.13.6"
      controlPlane: "1.13.6"
```

**Comment by ykakarap** [comment]
>resourcePool: "*/Physical-CAPV"

The `resourcePool` is probably the issue. I had the same issue. If 'Physical-CAPV' is the name of your resource pool then provide just 'Physical-CAPV' as `resourcePool` (without the "*/"). Providing the complete path like "*/Resources/<path>/<to>/<pool>/Physical-CAPV" also works. But using "*/Physical-CAPV" does not work.

Please re-try with just 'Physical-CAPV'.

**Comment by tkrausjr** [comment]
Thanks. Retried with updated Full Path for ResourcePool and VM Folder and same results. See updated machines.yaml.  Is there any logs or easy way to determine if the issue is with the bootstrap KIND cluster or the vSphere parameters ?

```
apiVersion: cluster.k8s.io/v1alpha1
kind: MachineList
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    name: "capv-mgmt-controlplane-1"
    labels:
      cluster.k8s.io/cluster-name: "capv-mgmt"
  spec:
    providerSpec:
      value:
        apiVersion: vsphere.cluster.k8s.io/v1alpha1
        kind: VsphereMachineProviderSpec
        datacenter: "Datacenter"
        datastore: "ISCSI-DATASTORE"
        resourcePool: "/Datacenter/host/Physical-OneNode/Resources/Physical-CAPV"
        folder: "/Datacenter/vm/capv_vms"
        network:
          devices:
          - networkName: "VLAN 1526"
            dhcp4: true
            dhcp6: false
        numCPUs: 2
        memoryMiB: 2048
        diskGiB: 20
        template: "ubuntu-1804-template"
    versions:
      kubelet: "1.13.6"
      controlPlane: "1.13.6"

```
