### ISSUE TITLE
Use generated instead of committed specs for pre-submit e2e test

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#444]
/kind feature

**Describe the solution you'd like**

Currently the e2e pre-submit uses spec files from [`./scripts/e2e/bootstrap_job/spec`](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/scripts/e2e/bootstrap_job/spec). However, this requires updating them every time any change occurs to CRDs, RBAC, etc.

This issue tracks the work required to use [`./hack/generate-yaml.sh`](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/hack/generate-yaml.sh) to generate the e2e specs at test-time instead of committing them as part of the index.

**Anything else you would like to add:**

Some things to note:

* The files in [`./scripts/e2e/bootstrap_job/spec`](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/scripts/e2e/bootstrap_job/spec) have a `.template` suffix instead of `.yaml` as they're interpolated with environment variables from a secure preset in the Prow build cluster.
* It **is** possible to generate specs with [`./hack/generate-yaml.sh`](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/hack/generate-yaml.sh) that use environment variables **for** environment variables. For example:

    ```shell
    VSPHERE_SERVER='$VSPHERE_SERVER' \
    VSPHERE_USERNAME='$VSPHERE_USERNAME' \
    VSPHERE_PASSWORD='$VSPHERE_PASSWORD' \
    VSPHERE_DATACENTER='SDDC-Datacenter' \
    VSPHERE_DATASTORE='WorkloadDatastore' \
    VSPHERE_NETWORK='sddc-cgw-network-5' \
    VSPHERE_RESOURCE_POOL='clusterapi' \
    VSPHERE_FOLDER='clusterapi' \
    VSPHERE_TEMPLATE='ubuntu-1804-kube-v1.13.6' \
    hack/generate-yaml.sh -c test1 -m '$VSPHERE_CONTROLLER_VERSION'
    ```

    The above command will generate the following cluster manifest at `out/test1/cluster.yaml` that is ready for re-interpolation for the server, username, and password values:

    ```yaml
    apiVersion: "cluster.k8s.io/v1alpha1"
    kind: Cluster
    metadata:
      name: test1
    spec:
      clusterNetwork:
        services:
          cidrBlocks: ["100.64.0.0/13"]
        pods:
          cidrBlocks: ["100.96.0.0/11"]
        serviceDomain: "cluster.local"
      providerSpec:
        value:
          apiVersion: vsphere.cluster.k8s.io/v1alpha1
          kind: VsphereClusterProviderSpec
          server: "$VSPHERE_SERVER"
          username: "$VSPHERE_USERNAME"
          password: "$VSPHERE_PASSWORD"
          sshAuthorizedKeys:
          - ""
    ```

    And a provider components manifest is generated at `out/test1/provider-components.yaml` with `$VSPHERE_CONTROLLER_VERSION` as the value of the CAPV manager image.

* The file [`./scripts/e2e/e2e.sh`](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/scripts/e2e/e2e.sh) is probably a good place to start looking as to where this generation should occur.
