### ISSUE TITLE
Documentation update in troubleshooting doc

### ISSUE THREAD

**Issue by jpweber** [kubernetes-sigs/cluster-api-provider-vsphere#479]
Under the Preferring an IP Address section the example yaml is as follows
```
network:
  devices:
  preferredAPIServerCidr: "192.168.5.0/24"
  - networkName: "sddc-cgw-network-6"
    ipAddrs:
    - 192.168.6.20/24
  - networkName: "sddc-cgw-network-5"
    dhcp4: true
```

`preferredAPIServerCidr: "192.168.5.0/24"` needs to be before `devices:` or after all the networks that are properties of `devices`.

A working exmaple
```
network:
  preferredAPIServerCidr: "192.168.5.0/24"
  devices:
  - networkName: "sddc-cgw-network-6"
    ipAddrs:
    - 192.168.6.20/24
  - networkName: "sddc-cgw-network-5"
    dhcp4: true
```
