### ISSUE TITLE
CentOS 7 OVA not accepting static ip

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#583]
/kind bug

**What steps did you take and what happened:**
Im trying to define my machines to use static IPs.
With the Ubuntu template this works fine, but with the centos template the same config with just the template exchanged fails to get its network interface up.
The vSphere Machine definition im using:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: VSphereMachine
metadata:
  name: management-cluster-controlplane-0
  namespace: default
spec:
  datacenter: Bremen
  diskGiB: 100
  memoryMiB: 8192
  network:
    devices:
      - dhcp4: false
        gateway4: 10.92.156.1
        ipAddrs:
          - 10.92.159.240/22
        nameservers:
          - 10.145.139.41
          - 10.145.139.42
        dhcp6: false
        networkName: VLAN151
  numCPUs: 4
  template: ubuntu-1804-kube-v1.15.3
```

**What did you expect to happen:**
The VM boots and gets an IP configured within the cloud-init process

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version:  0.5.1
- Kubernetes version: (use `kubectl version`):  1.15.3
- OS (e.g. from `/etc/os-release`):

**Comment by andrewsykim** [comment]
This is a known issue, please see https://github.com/kubernetes-sigs/image-builder/issues/48

**Comment by MnrGreg** [comment]
@MaxRink @akutz I found a small workaround for this which includes downing the interface and renaming it. This assumes the CentOS OVA with VMware vmxnet3 starts with interface name `ens192`. See the preKubeadmCommand below.

```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
spec:
  preKubeadmCommands:
  - if [[ $(cat /etc/os-release) =~ "CentOS" ]]; then ip link set ens192 down && ip link set ens192 name id0 && ifup id0 && nmcli con up "System id0"; fi
```

In addition the `dhcp4:false` flag within the `kind: VSphereMachine` network spec doesn't seem to work with cloud-init. `BOOTPROTO=dhcp` within the ifcfg-id0 is not altered. Again, one can manually work around this with the below. Just place it above the previous command so that its instantiated prior to the interface coming up.

```yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
spec:
  preKubeadmCommands:
  - sed -i -e 's/BOOTPROTO=dhcp/BOOTPROTO=static/g' /etc/sysconfig/network-scripts/ifcfg-id0
```

**Comment by MnrGreg** [comment]
After some digging it seems that with `Cloud-Init Network Config Version 2` the name of `Device Configuration ID` object is overwriting the ethernet interface device name within CentOS.

Example - Version 2 metadata:
```
instance-id: "management-cluster-controlplane-0"
network:
  version: 2
  ethernets:
    id0:
      match:
        macaddress: "00:50:56:a5:1a:78"
```

The results with the above are:
#### Centos 7.7 - not working:
- OS boots with default dynamic device name: /sys/class/net/ens192
- A udev rule file is created to rename the interface but it doesn't process unless the device is downed or server is rebooted. Note NAME="id0"
`/etc/udev/rules.d/70-persistent-net.rules`:
    ``SUBSYSTEM=="net", ACTION=="add", DRIVERS=="*?", ATTR{address}=="00:50:56:a5:b3:1f", NAME="id0"``
- An /etc/sysconfig/network-scripts/**ifcfg-id0** configuration file is created with cloud-init metadata. Note DEVICE=ID0:
![# Created by cloud-init on](https://user-images.githubusercontent.com/24388819/70101689-98e69400-15ea-11ea-9003-e4ff47b1b5f4.png)
- ip link shows ens192 UP but metadata static IP is not bound.
- nmcli connection shows ens192 down

#### Ubuntu 1804 - working:
- OS boots with default dynamic device name: /sys/class/net/ens192
- No udev rules are created in /etc/udev/rules.d/
- ip link shows ens192 UP with metadata static IP
- netplan is created under /etc/netplan/50-cloud-init.yaml:
```yaml
network:
    ethernets:
        id0:
            addresses:
            - 10.7.5.101/21
            dhcp4: false
            dhcp6: false
            gateway4: 10.7.7.254
            match:
                macaddress: 00:50:56:a5:12:e9
            nameservers:
                addresses:
                - 10.10.10.10
            wakeonlan: true
    version: 2
```

## Options to resolve:

1. Add the `set-name:` field to the Cloud-Init Network Config Version 2 specification within pkg/util/constants.go. Hardcode the value to "eth" + the device index (eth0) for each device instance.
2. Add the `set-name:` field to the Cloud-Init Network Config Version 2 specification within pkg/util/constants.go. Let the field be user configurable and drop if not specified.
3. Have upstream cloud-init and centos figure it out. ☹️  eish!


Example - Version 2 metadata with set-name:
```
instance-id: "management-cluster-controlplane-0"
network:
  version: 2
  ethernets:
    id0:
      match:
        macaddress: "00:50:56:a5:1a:78"
      set-name: "eth0"
```

The results with the above are:
#### CentOS 7.8 - working:
- OS boots with default dynamic device name: /sys/class/net/eth0
- A udev rules is created to rename the interface but doesnt process /etc/udev/rules.d/70-persistent-net.rules
    'SUBSYSTEM=="net", ACTION=="add", DRIVERS=="*?", ATTR{address}=="00:50:56:a5:b3:1f", NAME="eth0"'
- A /etc/sysconfig/network-scripts/ifcfg-**eth0** configuration file is created with cloud-init settings
- ip link shows eth0 UP with IP bound


#### Ubuntu 1804 - working:
- OS boots with default dynamic device name: /sys/class/net/eth0
- No udev rules are created in /etc/udev/rules.d/
- ip link shows eth0 UP
- netplan is created under /etc/netplan/50-cloud-init.yaml
```yaml
network:
    ethernets:
        id0:
            addresses:
            - 10.7.5.101/21
            dhcp4: false
            dhcp6: false
            gateway4: 10.7.7.254
            match:
                macaddress: 00:50:56:a5:12:e9
            nameservers:
                addresses:
                - 10.10.10.10
            set-name: eth0
            wakeonlan: true
    version: 2
```

@akutz @andrewsykim what are your thoughts on this?

Option 2 seems least intrusive while also giving more granular control. Should I put a PR together to review?
