### ISSUE TITLE
CAPV-generated Cert only includes first NIC address

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#663]
/kind bug

**What steps did you take and what happened:**
Im trying to get CAPV up and running with multiple NICs due to routing limitations of our Networks.
Ive assigend two NICs in the Controlplane.yml and selected one as preffered CIDR for the API

``` yml

 network:
    preferredAPIServerCidr: "10.88.168.0/24"
    devices:
      - networkName: VLAN339
        ipAddrs: 
          - "10.27.50.11/24"
        gateway4: "10.27.50.1"
        nameservers: 
          - "8.8.8.8"
        dhcp4: false
        dhcp6: false
      - networkName: VLAN340
        ipAddrs: 
          - "10.88.168.11/24"
        gateway4: "10.88.168.1"
        dhcp4: false
        dhcp6: false   

```

When i then boostrap the Cluster the boostrapping fails with this logline:
```E1118 16:00:22.678808       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile cloud config secret for VSphereCluster default/management-cluster: failed to create cloud provider secret for Cluster default/management-cluster: Post https://10.88.168.11:6443/api/v1/namespaces/kube-system/secrets: x509: certificate is valid for 100.64.0.1, 10.27.50.11, not 10.88.168.11"  "controller"="vspherecluster" "request"={"Namespace":"default","Name":"management-cluster"}```

So the API cert got issued for the wrong IP
**What did you expect to happen:**
The API Cert gets issued for the address within the specified "preferred CIDR"

**Environment:**

- Cluster-api-provider-vsphere version: 0.5.3
- Kubernetes version: (use `kubectl version`): 1.16.2
- OS (e.g. from `/etc/os-release`):  Ubuntu
