### ISSUE TITLE
Machine Stuck in "Provisioning"; capi-controller logs "Failed to parse ProviderID"

### ISSUE THREAD

**Issue by scottd018** [kubernetes-sigs/cluster-api-provider-vsphere#828]
/kind bug

**What steps did you take and what happened:**

Following the getting started guide to provision a cluster to vSphere (https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/getting_started.md).  The result was a **Machine** stuck in a **Provisioning** state and the following logs in the capi-controller:

```
E0312 19:45:12.439718       1 machine_controller_noderef.go:98] controllers/Machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "providerID"={} "node"="vsphere-quickstart-hp9w2.scott.net"
E0312 19:45:12.439762       1 machine_controller_noderef.go:98] controllers/Machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "providerID"={} "node"="vsphere-quickstart-md-0-76675f574-44b7g.scott.net"
E0312 19:45:12.439804       1 machine_controller.go:232] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="cannot assign NodeRef to Machine \"vsphere-quickstart-hp9w2\" in namespace \"default\", no matching Node: requeue in 10s" "cluster"="vsphere-quickstart" "machine"="vsphere-quickstart-hp9w2" "namespace"="default"
E0312 19:45:13.382162       1 machine_controller_noderef.go:98] controllers/Machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "providerID"={} "node"="vsphere-quickstart-hp9w2.scott.net"
E0312 19:45:13.382217       1 machine_controller_noderef.go:98] controllers/Machine "msg"="Failed to parse ProviderID" "error"="providerID is empty" "providerID"={} "node"="vsphere-quickstart-md-0-76675f574-44b7g.scott.net"
E0312 19:45:13.382264       1 machine_controller.go:232] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="cannot assign NodeRef to Machine \"vsphere-quickstart-md-0-76675f574-44b7g\" in namespace \"default\", no matching Node: requeue in 10s" "cluster"="vsphere-quickstart" "machine"="vsphere-quickstart-md-0-76675f574-44b7g" "namespace"="default"
```

The following steps were performed:

1) Create bootstrap cluster with kind
2) Create vsphere.yaml provider with my provider variables:

```
## -- Controller settings -- ##
VSPHERE_USERNAME: "my-admin-user"
VSPHERE_PASSWORD: "redcated-password"
## -- Required workload cluster default settings -- ##
VSPHERE_SERVER: "vcenter.scott.net"
VSPHERE_DATACENTER: "Scott-Home"
VSPHERE_DATASTORE: "vmw_vsan_v01hp"
VSPHERE_NETWORK: "26_external"
VSPHERE_RESOURCE_POOL: "Low-Priority"
VSPHERE_FOLDER: ""
VSPHERE_TEMPLATE: "centos7-kube-template-20200312000000"
VSPHERE_HAPROXY_TEMPLATE: "capv-haproxy-kube-template-20200312000000"
VSPHERE_SSH_AUTHORIZED_KEY: |
  <MY_PUBLIC_KEY_DATA>
```

3) Initialize the cluster:

`clusterctl init --infrastructure vsphere --config vsphere.yaml`

4) Create resource definition file with `clusterctl config cluster vsphere-quickstart --infrastructure vsphere --kubernetes-version v1.17.3 --control-plane-machine-count 1 --worker-machine-count 1 --config vsphere.yaml > test.yaml` .  Resource definition file is as follows:

**NOTE: manually removed sshAuthorizedKeys**
```
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: vsphere-quickstart
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: vsphere-quickstart
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereCluster
    name: vsphere-quickstart
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: HAProxyLoadBalancer
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: vsphere-quickstart
  name: vsphere-quickstart
  namespace: default
spec:
  user:
    authorizedKeys:
    name: capv
  virtualMachineConfiguration:
    cloneMode: linkedClone
    datacenter: Scott-Home
    datastore: vmw_vsan_v01hp
    diskGiB: 25
    folder: ""
    memoryMiB: 8192
    network:
      devices:
      - dhcp4: true
        networkName: 26_external
    numCPUs: 2
    resourcePool: Low-Priority
    server: vcenter.scott.net
    template: capv-haproxy-kube-template-20200312000000
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereCluster
metadata:
  name: vsphere-quickstart
  namespace: default
spec:
  cloudProviderConfiguration:
    global:
      insecure: true
      secretName: cloud-provider-vsphere-credentials
      secretNamespace: kube-system
    network:
      name: 26_external
    providerConfig:
      cloud:
        controllerImage: gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.0.0
      storage:
        attacherImage: quay.io/k8scsi/csi-attacher:v1.1.1
        controllerImage: gcr.io/cloud-provider-vsphere/csi/release/syncer:v1.0.2
        livenessProbeImage: quay.io/k8scsi/livenessprobe:v1.1.0
        metadataSyncerImage: gcr.io/cloud-provider-vsphere/csi/release/syncer:v1.0.2
        nodeDriverImage: gcr.io/cloud-provider-vsphere/csi/release/driver:v1.0.2
        provisionerImage: quay.io/k8scsi/csi-provisioner:v1.2.1
        registrarImage: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
    virtualCenter:
      vcenter.scott.net:
        datacenters: Scott-Home
    workspace:
      datacenter: Scott-Home
      datastore: vmw_vsan_v01hp
      folder: ""
      resourcePool: Low-Priority
      server: vcenter.scott.net
  loadBalancerRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: HAProxyLoadBalancer
    name: vsphere-quickstart
  server: vcenter.scott.net
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  name: vsphere-quickstart
  namespace: default
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: Scott-Home
      datastore: vmw_vsan_v01hp
      diskGiB: 25
      folder: ""
      memoryMiB: 8192
      network:
        devices:
        - dhcp4: true
          networkName: 26_external
      numCPUs: 2
      resourcePool: Low-Priority
      server: vcenter.scott.net
      template: centos7-kube-template-20200312000000
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: vsphere-quickstart
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereMachineTemplate
    name: vsphere-quickstart
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.hostname }}'
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
        name: '{{ ds.meta_data.hostname }}'
    preKubeadmCommands:
    - hostname "{{ ds.meta_data.hostname }}"
    - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
    - echo "127.0.0.1   localhost" >>/etc/hosts
    - echo "127.0.0.1   {{ ds.meta_data.hostname }}" >>/etc/hosts
    - echo "{{ ds.meta_data.hostname }}" >/etc/hostname
    users:
    - name: capv
      sudo: ALL=(ALL) NOPASSWD:ALL
  replicas: 1
  version: v1.17.3
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KubeadmConfigTemplate
metadata:
  name: vsphere-quickstart-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: /var/run/containerd/containerd.sock
          kubeletExtraArgs:
            cloud-provider: external
          name: '{{ ds.meta_data.hostname }}'
      preKubeadmCommands:
      - hostname "{{ ds.meta_data.hostname }}"
      - echo "::1         ipv6-localhost ipv6-loopback" >/etc/hosts
      - echo "127.0.0.1   localhost" >>/etc/hosts
      - echo "127.0.0.1   {{ ds.meta_data.hostname }}" >>/etc/hosts
      - echo "{{ ds.meta_data.hostname }}" >/etc/hostname
      users:
      - name: capv
        sudo: ALL=(ALL) NOPASSWD:ALL
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: vsphere-quickstart
  name: vsphere-quickstart-md-0
  namespace: default
spec:
  clusterName: vsphere-quickstart
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: vsphere-quickstart
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: vsphere-quickstart
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: vsphere-quickstart-md-0
      clusterName: vsphere-quickstart
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: VSphereMachineTemplate
        name: vsphere-quickstart
      version: v1.17.3
```

5) Machine is stuck in Provisioning, but machines are provisioned:

```
kubectl get machine
NAME                                      PROVIDERID                                       PHASE
vsphere-quickstart-hp9w2                  vsphere://422d3200-ea81-33d3-b30e-b3d439ca79aa   Provisioning
vsphere-quickstart-md-0-76675f574-44b7g   vsphere://422df8d9-985c-502c-1479-fca6ff3f03df   Provisioning
```

6) Download the kubeconfig, apply the CNI, and see status of nodes:

```
kubectl get secret/vsphere-quickstart-kubeconfig -o json   | jq -r .data.value   | base64 --decode   > ./vsphere-quickstart.kubeconfig
KUBECONFIG=vsphere-quickstart.kubeconfig kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

kubectl get nodes --kubeconfig vsphere-quickstart.kubeconfig
NAME                                                STATUS   ROLES    AGE    VERSION
vsphere-quickstart-hp9w2.scott.net                  Ready    master   147m   v1.17.3
vsphere-quickstart-md-0-76675f574-44b7g.scott.net   Ready    <none>   146m   v1.17.3
```

7) Logs seen in the capi-controller as noted in the description on top.

**What did you expect to happen:**

The command `kubectl get machine` would show the machines as either `Provisioned` or `Ready`.  The machine would only be `Ready` if there are no other issues found in the `Provisioned` state.

**Environment:**

- vSphere 6.7u3
- cluster-api v0.3.0
- gcr.io/cluster-api-provider-vsphere/release/manager:v0.6.0-rc.2
- From /etc/os-release (upstream provided images from Getting Started Guide were used for both HAproxy and CentOS Kube Template):

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
