### ISSUE TITLE
HAProxy does not fully support IPv6

### ISSUE THREAD

**Issue by frapposelli** [kubernetes-sigs/cluster-api-provider-vsphere#859]
/kind bug

**What steps did you take and what happened:**

Deploy a cluster with HAProxyLoadBalancer object with both `dhcp4` and `dhcp6` set to true

```
apiVersion: v1
items:
- apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
  kind: HAProxyLoadBalancer
[...]
  spec:
[...]
    virtualMachineConfiguration:
[...]
      network:
        devices:
        - dhcp4: true
          dhcp6: true
          networkName: VMNetPG
[...]
```

And the VM will come up without getting an IPv6 address, then K8s nodes will come up with both ipv4 and ipv6 addresses and they will be listed in the `/etc/haproxy/haproxy.cfg` rendering.

**What did you expect to happen:**

The HAProxy vm to come up with both ipv4 and ipv6 addresses and to work seamlessly.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version:  v0.6.2
- Kubernetes version: (use `kubectl version`):  1.17.3
- OS (e.g. from `/etc/os-release`):  
```
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```
