### ISSUE TITLE
Remove dependency for API access of Clusters

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#924]
/kind feature

**Describe the solution you'd like**
Currently all clusters created by CAPV have the vsphere-cloud-controller-manager installed, even if i strip out all other CSI components.
Without vsphere-cloud-controller-manager nodes dont get marked as ready thus a 2nd or 3rd master node never get provisioned for example.

From my understanding vsphere-cloud-controller-manager only does the following things in a non-CSI cluster:
 - removing the node.cloudprovider.kubernetes.io/uninitialized taint
- adding the beta.kubernetes.io/instance-type label
- adding the providerID: vsphere://...

All of which, even the providerID ( https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#update-all-node-providerid-fields ), could be done outside the cluster, thus making Clusters possible that dont have access to the api of the cluster they are running on, thus improving security.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by MaxRink** [comment]
im currently using thsi script to manually trigger the correct data being present

```

export GOVC_USERNAME='user'
export GOVC_INSECURE=1
export GOVC_PASSWORD='pw'
export GOVC_URL='server'
DATACENTER='DC'
FOLDER=Folder'

# In my case I'm using a prefix for the VM's, so grep'ing is necessary.
# You can remove it if the folder you are using only contains the machines you need.
VM_PREFIX='smops'
IFS=$'\n'
for vm in $(govc ls "/$DATACENTER/vm/$FOLDER" | grep $VM_PREFIX); do
  MACHINE_INFO=$(govc vm.info -json -dc=$DATACENTER -vm.ipath="/$vm" -e=true)
  # My VMs are created on vmware with upper case names, so I need to edit the names with awk
  VM_NAME=$(jq -r ' .VirtualMachines[] | .Name' <<< $MACHINE_INFO | awk '{print tolower($0)}')
  # UUIDs come in lowercase, upper case then
  VM_UUID=$( jq -r ' .VirtualMachines[] | .Config.Uuid' <<< $MACHINE_INFO | awk '{print toupper($0)}')
  echo "Patching $VM_NAME with UUID:$VM_UUID"
  # This is done using dry-run to avoid possible mistakes, remove when you are confident you got everything right.
  kubectl patch node $VM_NAME -p "{\"spec\":{\"providerID\":\"vsphere://$VM_UUID\"}}"
  kubectl taint nodes $VM_NAME node.cloudprovider.kubernetes.io/uninitialized-
done

```

**Comment by ncdc** [comment]
@yastij have you thought about moving the deployment of CCM/CPI/etc to a ClusterResourceSet, once they're available? That should solve this request (assuming one has a separate controller to set the provider ID and remove the taint).

**Comment by yastij** [comment]
@ncdc - that can be a solution. I'm also thinking about what it would take to run the CPI ias part of the management cluster

**Comment by MaxRink** [comment]
Just verfified that running the CCM from the management cluster works

**Comment by MaxRink** [comment]
So, here is my yaml-file that 

i used to run the ccm from the mgmt cluster:
[external-ccm-san.yaml.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4821091/external-ccm-san.yaml.txt)
One thing i havent gotten to work with the this PoC: grabbing the vsphere credentials from a secret insetad out of a configmap.
That always gave me this errors. Directly in the config everything works fione tho.
```
W0623 17:57:12.514429       1 credentialmanager.go:85] Cannot get secret vsphere-cpi in namespace bremen. error: "secret \"vsphere-cpi\" not found"
E0623 17:57:12.514437       1 credentialmanager.go:54] updateCredentialsMapK8s failed. err=secret "vsphere-cpi" not found
W0623 17:57:12.514443       1 credentialmanager.go:60] secret "vsphere-cpi" not found in namespace "bremen"
E0623 17:57:12.514448       1 credentialmanager.go:75] credentials not found for server vcenter1.sce-dcn.net
```

**Comment by randomvariable** [comment]
Suspect it's not using local object reference to grab the secret and ended up in the wrong namespace. Possibly a bug for the vsphere provider.

**Comment by MaxRink** [comment]
Might be. unfortuinately even with -v=10 i font get more logoutput regarding that error.

**Comment by fabriziopandini** [comment]
@MaxRink I'm reporting here the TL;DR from the slack thread, please correct me if there is something incomplete or wrong.

- CAPV allows to opt-out from CSI and CCM installation via API config
- Without CCM, nodes do not get ready, so we are exploring the installation of CCM in the management cluster
- installation of CCM in the management cluster happens via the git-ops tooling, in sync with the creation of the workload cluster (1 instance of CCM for each workload cluster)
- the only problem pending is how to pass vSphere credential to CCM instances, due to a bug in using secrets. While this gets fixes in CCM, a possible workaround is to set env variables from the secret, and then let CCM use credentials from env variables, but this should be tested

**Comment by sathieu** [comment]
@srm09 @MaxRink @yastij WDYT about my proposed ways forward? I can propose a PR for solution 1 (solution 2 is harder for me, and solution 3 means a new repo probably).

**Comment by sathieu** [comment]
Here is another way to set `providerID`, using `.status.nodeInfo.systemUUID`:

```sh
export KUBECONFIG=/etc/kubernetes/admin.conf  # if called from controlplane 1
while read -r node_name node_systemuuid current_providerid ; do
  expected_providerid="vsphere://${node_systemuuid:6:2}${node_systemuuid:4:2}${node_systemuuid:2:2}${node_systemuuid:0:2}-${node_systemuuid:11:2}${node_systemuuid:9:2}-${node_systemuuid:16:2}${node_systemuuid:14:2}-${node_systemuuid:19:4}-${node_systemuuid:24:12}"
  if [ "$current_providerid" != "$expected_providerid" ]; then
    echo "$node_name: .spec.providerID $current_providerid -> $expected_providerid"
    kubectl patch node "$node_name" -p '{"spec": {"providerID": "'"$expected_providerid"'"}}'
  fi
done < <(kubectl  get nodes --output=custom-columns=NAME:.metadata.name,SYSTEMUUID:.status.nodeInfo.systemUUID,PROVIDERID:.spec.providerID --no-headers=true)
```

**Comment by sathieu** [comment]
Here is a more automatic way to do this:

```yaml
# in KubeadmConfigTemplate.spec.template.spec and KubeadmControlPlane.spec.kubeadmConfigSpec
        postKubeadmCommands:
          051_run-post-kubeadm-commands: for script in $(find /etc/post-kubeadm-commands/ -name '*.sh' -type f | sort);
            do echo "Running script $script"; "$script"; done
        files:
          - path: /etc/post-kubeadm-commands/vsphere-providerid.sh:
            content: |
              #!/bin/bash

              set -e

              grep -qi vmware /sys/class/dmi/id/sys_vendor || exit 0

              # https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/924
              node_name="$(hostname)"
              node_systemuuid="$(KUBECONFIG=/etc/kubernetes/kubelet.conf kubectl get node "$node_name" '-ojsonpath={.status.nodeInfo.systemUUID}')"
              expected_providerid="vsphere://${node_systemuuid:6:2}${node_systemuuid:4:2}${node_systemuuid:2:2}${node_systemuuid:0:2}-${node_systemuuid:11:2}${node_systemuuid:9:2}-${node_systemuuid:16:2}${node_systemuuid:14:2}-${node_systemuuid:19:4}-${node_systemuuid:24:12}"
              KUBECONFIG=/etc/kubernetes/kubelet.conf kubectl patch node "$node_name" -p '{"spec": {"providerID": "'"$expected_providerid"'"}}'
            owner: root:root
            permissions: "0700"
```
