### ISSUE TITLE
Cannot deploy k8s 1.12.x with current code

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#97]
The kubeadm template config schema has changed in a non backwards compatible way from 1.11.x to 1.12.x  The current kubeadm template inside our code is only compatible uptill 1.11.x and breaks for k8s 1.12.x

**Comment by neolit123** [comment]
is this the code in question?
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/pkg/cloud/vsphere/provisioner/common/templates.go#L482

chronology:
- pre-1.11 - v1alpha1
- 1.11 - v1alpha2
- 1.12 - v1alpha3
- 1.13 - v1beta1 (TBD)

the API (config) is ever changing because it's still under development.
a MINOR release of kubeadm includes a tool called `kubeadm config migrate` that can be used to translate a config from the MINOR-1 to the current MINOR.

here is the v1alpha3 config that is the default one for 1.12.
```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: v${CONTROL_PLANE_VERSION}
networking:
  serviceSubnet: ${SERVICE_CIDR}
  podSubnet: ${POD_CIDR}
apiServerCertSANs:
- ${PUBLICIP}
- ${PRIVATEIP}
apiServerExtraArgs:
  cloud-provider: vsphere
  cloud-config: /etc/kubernetes/cloud-config/cloud-config.yaml
apiServerExtraVolumes:
- name: cloud-config
  hostPath: /etc/kubernetes/cloud-config
  mountPath: /etc/kubernetes/cloud-config
controllerManagerExtraArgs:
  cloud-provider: vsphere
  cloud-config: /etc/kubernetes/cloud-config/cloud-config.yaml
  address: 0.0.0.0
schedulerExtraArgs:
  address: 0.0.0.0
controllerManagerExtraVolumes:
- name: cloud-config
  hostPath: /etc/kubernetes/cloud-config
  mountPath: /etc/kubernetes/cloud-config
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
apiEndpoint:
  advertiseAddress: ${PUBLICIP}
  bindPort: ${PORT}
```

on a side note, the above config subset subset should be compatible between v1alpha3 and v1beta1, so `/v1alpha3/v1beta1/s`.
