### ISSUE TITLE
vsphere password starts with an "@"

### ISSUE THREAD

**Issue by zawachte-msft** [kubernetes-sigs/cluster-api-provider-vsphere#980]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Following the CAPV quickstart steps. CAPV pod comes up fine, but when it gets to machine creation, API calls to the vcenter were failing.

Logs pointed towards...
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/pkg/manager/options.go#L165

Turns out a yaml value field can't start with "@".  https://tex.stackexchange.com/questions/148994/problem-found-character-that-cannot-start-any-token

As a workaround, I patched the creds secret and wrapped my password in quotes. Then the deployment succeeded.

Not sure if a fix needs to be taken, but I figured I would point out this issue.

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
@zawachte-msft could you please provide an example of the before & after versions (please obfuscate/redact anything sensitive)?

**Comment by randomvariable** [comment]
I think we would want to ensure there's quotes around the relevant parts in this part of infrastructure-components:

``` yaml
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
  name: capv-manager-bootstrap-credentials
  namespace: capv-system
stringData:
  credentials.yaml: |-
    username: ${VSPHERE_USERNAME}
    password: ${VSPHERE_PASSWORD}
```
should be

```yaml 
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
  name: capv-manager-bootstrap-credentials
  namespace: capv-system
stringData:
  credentials.yaml: |-
    username: "${VSPHERE_USERNAME}"
    password: "${VSPHERE_PASSWORD}"
```

backtick and `@` are sigils reserved for future use in the yaml spec.
